# 1. Сборка приложения
FROM node:20-alpine AS build
WORKDIR /app

# Шаг 1: Копируем файлы манифеста и устанавливаем зависимости
# Это важно для кэширования: если package.json не меняется, npm install не запускается заново
COPY package.json .
COPY package-lock.json .
RUN npm install

# Шаг 2: Копируем остальные файлы исходного кода
COPY . .

# Шаг 3: Выполняем сборку
RUN npm run build

# 2. Обслуживание статики (через Nginx)
FROM nginx:alpine
# *** ИЗМЕНЕНИЕ ЗДЕСЬ ***
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]